name: Static Analysis

on: [push, pull_request]

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Compile contracts
        run: forge build --force

      - name: Run Slither
        uses: crytic/slither-action@v0.1.1
        with:
          ignore-compile: true
          node-version: 16
          slither-config: ./slither.config.json
          slither-version: v0.8.3
